<?php

namespace Database\Seeders;

use App\Models\Team;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class TeamsSeeder extends Seeder
{
    public function run(): void
    {

        $teams = [
            ['team_id' => 1, 'name' => 'Milwaukee Bucks',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612749/global/L/logo.svg',
             'division' => 'Central',
             'conference' => 'Eastern',
             'city' => 'Milwaukee',
             'arena' => 'Fiserv Forum',
             'head_coach' => 'Doc Rivers',
             'lead_assistant_coach'=> 'David Joerger',
             'assitant_coach' => 'David Joerger, 
                Vin Baker, 
                Rex Kalamian, 
                Darvin Ham, 
                Greg Buckner, 
                Jason Love, 
                Pete Dominguez, 
                Spencer Rivers, 
                Jack Herum',
             'trainer' => 'Scott Faust',
             'founded' => 1968,
             'championships' => 3
            ],

            ['team_id' => 2, 'name' => 'Dallas Mavericks',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612742/global/L/logo.svg',
             'division' => 'Southwest',
             'conference' => 'Western',
             'city' => 'Dallas',
             'arena' => 'American Airlines Center',
            'head_coach'=> 'Jason Kidd',
            'lead_assistant_coach'=> 'Frank Vogel',
            'assitant_coach'=> 
                'Frank Vogel, 
                Jay Triano, 
                Popeye Jones, 
                Phil Handy, 
                Mike Penberthy, 
                Eric Hughes, 
                Josh Broghamer, 
                Dru Anthrop, 
                Keith Veney, 
                Jordan Sears',
             'trainer'=> 'Jana Austin',
             'founded' => 1980,
             'championships' => 1
            ],

            ['team_id' => 3, 'name' => 'Toronto Raptors',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612761/global/L/logo.svg',
             'division' => 'Atlantic',
             'conference' => 'Eastern',
             'city' => 'Toronto',
             'arena' => 'Scotiabank Arena',
             'head_coach' => 'Darko Rojakovic',
             'assistant_coach' =>
                'Pat Delany, 
                Mike Batiste,
                Vin Bhavnani,
                Jim Sann,
                James Wade,
                Jama Mahlalela,
                Mery Andreade,
                Ivo Simovic',
             'trainer' => 'Rayhan Malik',
             'founded' => 1995,
             'championships' => 1
            ],

            ['team_id' => 4, 'name' => 'Denver Nuggets',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612743/global/L/logo.svg',
             'division' => 'Northwest',
             'conference' => 'Western',
             'city' => 'Denver',
             'arena' => 'Ball Arena',
             'head_coach' => 'David Adelman',
             'assistant_coach' => 
                'Jared Dudley,
                Chase Buford,
                John Beckett,
                Ognjen Stojakovic,
                Elvis Valcarel',
             'trainer' => 'Dan Shimensky',
             'founded' => 1976,
             'championships' => 1
            ],

            ['team_id' => 5, 'name' => 'Houston Rockets',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612745/global/L/logo.svg',
             'division' => 'Southwest',
             'conference' => 'Western',
             'city' => 'Houston',
             'arena' => 'Toyota Center',
             'head_coach' => 'Ime Udoka',
             'assistant_coach' => 
                'Ben Sullivan,
                Royal Ivey,
                Garrett Jackson,
                Cam Hodges,
                Mike Moser,
                Robbie Lemons,
                Josh Bostic',
             'trainer' => 'Jason Biles',
             'founded' => 1971,
             'championships' => 2
            ],

            ['team_id' => 6, 'name' => 'Indiana Pacers',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612754/global/L/logo.svg',
             'division' => 'Central',
             'conference' => 'Eastern',
             'city' => 'Indiana',
             'arena' => 'Gainbridge Fieldhouse',
             'head_coach'=> 'Rick Carlisle',
             'lead_assistant_coach'=> 'Lloyd Pierce',
             'assitant_coach'=> 'Jim Boylen, 
                Johnny Carpenter, 
                Jenny Boucek, 
                Jannero Pargo, 
                Maurice Baker, 
                Isaac Yacob',
             'trainer'=> 'Josh Corbeil',
             'founded' => 1976,
             'championships' => 0
            ],

            ['team_id' => 7, 'name' => 'Oklahoma City Thunder',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612760/global/L/logo.svg',
             'division' => 'Northwest',
             'conference' => 'Western',
             'city' => 'Oklahoma City',
             'arena' => 'Paycom Center',
             'head_coach' => 'Mark Daigneault',
             'assitant_coach' => 
                'Grant Gibbs,
                Mike Wilks,
                Chip Engelland,
                Eric Maynor,
                David Akinyooye,
                Dave Bliss,
                Zoe Vernon',
             'ACPD' => 'Connor Johnson',
             'trainer' => 'Donnie Strack',
             'general_manager' => 'Sam Presti',
             'founded' => 2008,
             'championships' => 1
            ],

            ['team_id' => 8, 'name' => 'Utah Jazz',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612762/global/L/logo.svg',
             'division' => 'Northwest',
             'conference' => 'Western',
             'city' => 'Salt Lake City',
             'arena' => 'Vivint Arena',
             'head_coach'=> 'Will Hardy',
             'lead_assistant_coach'=> 'Chad Forcier',
             'assitant_coach'=> 
                'Chad Forcier, 
                Scott Morrison, 
                Sean Sheldon, 
                Jason Terry, 
                Chris Jones, 
                Andrew Warren, 
                Mike Williams, 
                Steve Wojciechowski',
             'trainer'=> 'Jamal Cort',
             'founded' => 1974,
             'championships' => 0
            ],

            ['team_id' => 9, 'name' => 'Philadelphia 76ers',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612755/global/L/logo.svg',
             'division' => 'Atlantic',
             'conference' => 'Eastern',
             'city' => 'Philadelphia',
             'arena' => 'Wells Fargo Center',
             'head_coach'=> 'Nick Nurse',
             'lead_assistant_coach'=> 'Rico Hines',
             'assitant_coach'=> 
                'Rico Hines, 
                Coby Karl, 
                Mike Longabardi, 
                Bryan Gates, 
                Matt Brase, 
                Doug West',
             'trainer'=> 'Kevin Johnson',
             'founded' => 1946,
             'championships' => 3
            ],

            ['team_id' => 10, 'name' => 'Los Angeles Lakers',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612747/global/L/logo.svg',
             'division' => 'Pacific',
             'conference' => 'Western',
             'city' => 'Los Angeles',
             'arena' => 'Crypto.com Arena',
             'head_coach' => 'JJ Redick',
             'assistant_coach' => 
                'Nate McMillan,
                Scott Brooks,
                Bob Beyer,
                Greg St. Jean,
                Lindsey Harding,
                Beau Levesque',
             'trainer' => 'Vannesa Brooks',
             'founded' => 1948,
             'championships' => 17
            ],

            ['team_id' => 11, 'name' => 'Golden State Warriors',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612744/global/L/logo.svg',
             'division' => 'Pacific',
             'conference' => 'Western',
             'city' => 'San Francisco',
             'arena' => 'Chase Center',
             'head_coach'=> 'Steve Kerr',
             'lead_assistant_coach'=> 'Bruce Fraser',
             'assitant_coach'=> 'Bruce Fraser, 
                Seth Cooper, 
                Jerry Stackhouse, 
                Terry Stotts, 
                Ron Adams, 
                Anthony Vereen, 
                Kris Weems, 
                Jacob Rubin, 
                Nick Kerr, 
                Khalid Robinson',
             'trainer'=> 'Drew Yoder',
             'founded' => 1946,
             'championships' => 4
            ],

            ['team_id' => 12, 'name' => 'Orlando Magic',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612753/global/L/logo.svg',
             'division' => 'Southeast',
             'conference' => 'Eastern',
             'city' => 'Orlando',
             'arena' => 'Amway Center',
             'head_coach'=> 'Jamahl Mosley',
             'lead_assistant_coach'=> 'Joe Prunty',
             'assitant_coach'=> 
                'Joe Prunty, 
                Dale Osbourne, 
                Bret Brielmaier, 
                God Shammgod, 
                Randy Gregory, 
                Lionel Chalmers',
             'trainer'=> 'Ernest Eugene',
             'founded' => 1989,
             'championships' => 0
            ],

            ['team_id' => 13, 'name' => 'Washington Wizards',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612764/global/L/logo.svg',
             'division' => 'Southeast',
             'conference' => 'Eastern',
             'city' => 'Washington, D.C.',
             'arena' => 'Capital One Arena',
             'head_coach'=> 'Brian Keefe',
             'lead_assistant_coach'=> 'Alexis Ajinca',
             'assitant_coach'=> 'Alexis Ajinca, 
                David Vanterpool, 
                J.J. Outlaw, 
                Adam Caporn, 
                James Fraschilla, 
                T.J. Sorrentine',
             'trainer'=> 'Michael Ashton',
             'founded' => 1961,
             'championships' => 1
            ],

            ['team_id' => 14, 'name' => 'Boston Celtics',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612738/global/L/logo.svg',
             'division' => 'Atlantic',
             'conference' => 'Eastern',
             'city' => 'Boston',
             'arena' => 'TD Garden',
             'head_coach' => 'Joe Mazzulla',
             'assistant_coach' => 
                'Amile Jefferson, 
                D.J. MacLeay,
                Matt Reynolds,
                Tony Dobbins,
                Sam Cassell',
             'trainer' => 'Drew Moore',
             'Strength and Conditioning Coach' => 'Jordan Sabourin',
             'founded' => 1946,
             'championships' => 17
            ],

            ['team_id' => 15, 'name' => 'Phoenix Suns',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612756/global/L/logo.svg',
             'division' => 'Pacific',
             'conference' => 'Western',
             'city' => 'Phoenix',
             'arena' => 'Footprint Center',
             'head_coach' => 'MJordan Ott',
             'assistant_coach' => 
                'Brian Randle,
                Chaisson Allen,
                John Little,
                Sean Dwyer,
                Demarre Carroll,
                Mike Muscala,
                Jesse Mermuys',
             'trainer' => 'Roger Sancho',
             'founded' => 1968,
             'championships' => 0
            ],

            ['team_id' => 16, 'name' => 'Miami Heat',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612748/global/L/logo.svg',
             'division' => 'Southeast',
             'conference' => 'Eastern',
             'city' => 'Miami',
             'arena' => 'FTX Arena',
             'head_coach'=> 'Erik Spoelstra',
             'lead_assistant_coach'=> 'Caron Butler',
             'assitant_coach'=> 
                'Caron Butler, 
                Wayne Ellington, 
                Chris Quinn, 
                Malik Allen, 
                Eric Glass, 
                Octavio De La Grana',
             'trainer'=> 'Wes Brown',
             'founded' => 1988,
             'championships' => 3
            ],

            ['team_id' => 17, 'name' => 'Chicago Bulls',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612741/global/L/logo.svg',
             'division' => 'Central',
             'conference' => 'Eastern',
             'city' => 'Chicago',
             'arena' => 'United Center',
             'head_coach'=> 'Billy Donovan',
             'lead_assistant_coach'=> 'Henry Domercant',
             'assitant_coach'=> 'Henry Domercant, 
                Damian Cotter, 
                Wes Unseld, 
                John Bryant, 
                Dan Craig, 
                Billy Schmidt',
             'trainer'=> 'Todd Campbell',
             'founded' => 1966,
             'championships' => 6
            ],

            ['team_id' => 18, 'name' => 'Minnesota Timberwolves',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612750/global/L/logo.svg',
             'division' => 'Northwest',
             'conference' => 'Western',
             'city' => 'Minneapolis',
             'arena' => 'Target Center',
             'head_coach' => 'Chris Finch',
             'assistant_coach' => 
                'Pablo Prigioni,
                Chris Hines,
                Kevin Hansons,
                Jeff Newton,
                Elson Tuner,
                Micah Nori,
                Max Lefevre',
             'trainer' => 
                'Gregg Farnam,
                Erin Sierer',
             'founded' => 1989,
             'championships' => 0
            ],

            ['team_id' => 19, 'name' => 'Charlotte Hornets',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612766/global/L/logo.svg',
             'division' => 'Southeast',
             'conference' => 'Eastern',
             'city' => 'Charlotte',
             'arena' => 'Spectrum Center',
             'head_coach'=> 'Charles Lee',
             'lead_assistant_coach'=> 'Lamar Skeeter',
             'assitant_coach'=> 'Lamar Skeeter, 
                Joshua Longstaff, 
                Blaine Mueller, 
                Ryan Frazier, 
                Matt Hill, 
                Jermaine Bucknor, 
                Kyle Neptune, 
                Zach Peterson, 
                Kemba Walker',
            'trainer'=> 'Peter Elliott',
             'founded' => 1988,
             'championships' => 0
            ],

            ['team_id' => 20, 'name' => 'New York Knicks',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612752/global/L/logo.svg',
             'division' => 'Atlantic',
             'conference' => 'Eastern',
             'city' => 'New York',
             'arena' => 'Madison Square Garden',
             'head_coach' => 'Mike Brown',
             'assistant_coaches' => 
                'Andy Greer,
                Chris Jent,
                Brendan O.Connor,
                Mark Bryant,
                Rick Brunson,
                Darren Erman,
                TJ Saint,
                Maurice Cheeks,
                Riccardo Fois',
             'ACPD' => 'Dice Yoshimoto',
             'trainer' => 
                'Anthony Goenaga',
                'Roger Hinds',
             'founded' => 1946,
             'championships' => 2
            ],

            ['team_id' => 21, 'name' => 'Atlanta Hawks',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612737/global/L/logo.svg',
             'division' => 'Southeast',
             'conference' => 'Eastern',
             'city' => 'Atlanta',
             'arena' => 'State Farm Arena',
             'head_coach'=> 'Quin Snyder',
             'lead_assistant_coach'=> 'Ronald Nored',
             'assitant_coach'=> 
                'Ronald Nored, 
                Antonio Lang, 
                Jeff Watkinson, 
                Igor Kokoskov, 
                Ekpe Udoh, 
                Bryan Bailey, 
                Ryan Schmidt, 
                Sanjay Lumpkin, 
                Mike Brey, 
                Reggis Onwukamuche',
             'trainer'=> 'Scottie Parker',
             'founded' => 1946,
             'championships' => 1
            ],

            ['team_id' => 22, 'name' => 'Detroit Pistons',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612765/global/L/logo.svg',
             'division' => 'Central',
             'conference' => 'Eastern',
             'city' => 'Detroit',
             'arena' => 'Little Caesars Arena',
             'head_coach' => 'J.B. Bickerstaff',
             'assistant_coach' => 
                'Jarrett Jack, 
                Fred Vinson,
                Vitaly Potapenko,
                Steve Scalzi,
                Luke Walton,
                Jerome Allen,
                Kevin Burleson,
                Sidney Lowe,
                Greg Smith,
                Josh Estes',
             'trainer' => 'Alex Garland',
             'founded' => 1957,
             'championships' => 3
            ],

            ['team_id' => 23, 'name' => 'Brooklyn Nets',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612751/global/L/logo.svg',
             'division' => 'Atlantic',
             'conference' => 'Eastern',
             'city' => 'Brooklyn',
             'arena' => 'Barclays Center',
             'head_coach'=> 'Jordi Fernandez',
             'lead_assistant_coach'=> 'Steve Hetzel',
             'assitant_coach'=> 
                'Steve Hetzel, 
                Juwan Howard, 
                Jay Hernandez, 
                Dutch Gaitley, 
                Deividas Dulkys, 
                Ryan Forehan-Kelly, 
                Connor Griffin, 
                Corey Vinson, 
                Travis Bader',
             'trainer'=> 'Geoffrey Staton',
             'founded' => 1967,
             'championships' => 0
            ],

            ['team_id' => 24, 'name' => 'Los Angeles Clippers',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612746/global/L/logo.svg',
             'division' => 'Pacific',
             'conference' => 'Western',
             'city' => 'Los Angeles',
             'head_coach'=> 'Tyronn Lue',
             'lead_assistant_coach'=> 'Jeff Van Gundy',
             'assitant_coach'=> 
                'Dahntay Jones, 
                Brian Shaw, 
                Jay Larranaga, 
                Shaun Fein, 
                Jeremy Castleberry, 
                Chris Holguin, 
                Tim Dather, 
                Conor Dunleavy, 
                Larry Drew',
             'trainer'=> 'Jasen Powell',
             'founded' => 1970,
             'championships' => 0
            ],

            ['team_id' => 25, 'name' => 'San Antonio Spurs',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612759/global/L/logo.svg',
             'division' => 'Southwest',
             'conference' => 'Western',
             'city' => 'San Antonio',
             'arena' => 'AT&T Center',
             'head_coach' => 'Mitch Johnson',
             'Associate Head Coach' => 'Sean Sweeney',
             'Assistant Coach' =>
                'Corliss Williamson,
                Mike Noyes,
                Scott King,
                Matt Nielsen',
             'trainer' => 'Will Sevening',
             'founded' => 1973,
             'championships' => 5
            ],

            ['team_id' => 26, 'name' => 'Portland Trail Blazers',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612757/global/L/logo.svg',
             'division' => 'Northwest',
             'conference' => 'Western',
             'city' => 'Portland',
             'arena' => 'Moda Center',
             'head_coach'=> 'Chauncey Billups',
             'lead_assistant_coach'=> 'Tiago Splitter',
             'assitant_coach'=> 
                'Tiago Splitter, 
                Nate Bjorkgren, 
                James Posey, 
                Pat St. Andrews, 
                Quinton Crawford, 
                Ronnie Burrell',
             'trainer'=> 'Jessica Cohen',
             'founded' => 1970,
             'championships' => 1
            ],

            ['team_id' => 27, 'name' => 'Memphis Grizzlies',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612763/global/L/logo.svg',
             'division' => 'Southwest',
             'conference' => 'Western',
             'city' => 'Memphis',
             'arena' => 'FedExForum',
             'head_coach' => 'Tuomas Iisalo',
             'lead_assistant_coach' => 'Erik Schmidt',
             'assitant_coach' => 
                'Erik Schmidt, 
                Darnell Lazare, 
                Ryan Saunders, 
                Jason March, 
                Brian Collins',
             'trainer' => 'Eric Oetter',
             'founded' => 1995,
             'championships' => 0
            ],

            ['team_id' => 28, 'name' => 'New Orleans Pelicans',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612740/global/L/logo.svg',
             'division' => 'Southwest',
             'conference' => 'Western',
             'city' => 'New Orleans',
             'arena' => 'Smoothie King Center',
             'head_coach' => 'James Borrego',
             'lead_assistant_coach' => 'Jarron Collins',
             'assitant_coach' => 
                'Jarron Collins, 
                Casey Hill, 
                Aaron Miles, 
                Corey Brewer, 
                Jodie Meeks',
             'trainer' => 'Tom Maystadt',
             'founded' => 2002,
             'championships' => 0
            ],

            ['team_id' => 29, 'name' => 'Cleveland Cavaliers',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612739/global/L/logo.svg',
             'division' => 'Central',
             'conference' => 'Eastern',
             'city' => 'Cleveland',
             'arena' => 'Rocket Mortgage FieldHouse',
             'head_coach' => 'Kenny Atkinson',
             'lead_assistant_coach' => 'Johnnie Bryant',
             'assitant_coach' => 
                'Mike Gerrity, 
                Trevor Hendry, 
                Alex Sarama, 
                Jawad Williams, 
                Omar Cook, 
                Nate Reinking, 
                Andrew Olson',
             'trainer' => 'Stephen Spiro',
             'founded' => 1970,
             'championships' => 1
            ],

            ['team_id' => 30, 'name' => 'Sacramento Kings',
             'logo_url' => 'https=>//cdn.nba.com/logos/nba/1610612758/global/L/logo.svg',
             'division' => 'Pacific',
             'conference' => 'Western',
             'city' => 'Sacramento',
             'arena' => 'Golden 1 Center',
             'head_coach' => 'Doug Christie',
             'lead_assistant_coach' => 'Mike Woodson',
             'assitant_coach' => 
                'Leandro Barbosa, 
                Bobby Jackson, 
                Mike Miller, 
                Chris Darnell, 
                Dipesh Mistry, 
                Garrius Adams, 
                Jimmy Alapag',
             'trainer' => 'Joel Noland',
             'founded' => 1945,
             'championships' => 1
            ],
        ];
      foreach ($teams as $team) {
         if (isset($team['logo_url'])) {
            $team['logo_url'] = str_replace('https=>//', 'https://', $team['logo_url']);
         }

         if (isset($team['assitant_coach']) && ! isset($team['assistant_coach'])) {
            $team['assistant_coach'] = $team['assitant_coach'];
         }

         if (isset($team['assistant_coaches']) && ! isset($team['assistant_coach'])) {
            $team['assistant_coach'] = $team['assistant_coaches'];
         }

         if (isset($team['Assistant Coach']) && ! isset($team['assistant_coach'])) {
            $team['assistant_coach'] = $team['Assistant Coach'];
         }

         if (isset($team['Associate Head Coach']) && ! isset($team['lead_assistant_coach'])) {
            $team['lead_assistant_coach'] = $team['Associate Head Coach'];
         }

         if (isset($team['ACPD']) && ! isset($team['coach_development'])) {
            $team['coach_development'] = $team['ACPD'];
         }

         if (isset($team['Strength and Conditioning Coach']) && ! isset($team['trainer_assistant'])) {
            $team['trainer_assistant'] = $team['Strength and Conditioning Coach'];
         }

         unset($team['assitant_coach'], $team['assistant_coaches']);

         $team = Arr::only($team, [
            'team_id',
            'name',
            'logo_url',
            'division',
            'conference',
            'city',
            'arena',
            'head_coach',
            'lead_assistant_coach',
            'assistant_coach',
            'trainer',
            'trainer_assistant',
            'coach_development',
            'owner',
            'general_manager',
            'founded',
            'championships',
            'gp',
            'w',
            'l',
            'w_pct',
            'min',
            'pts',
            'fgm',
            'fga',
            'fg_pct',
            'fg3m',
            'fg3a',
            'fg3_pct',
            'ftm',
            'fta',
            'ft_pct',
            'oreb',
            'dreb',
            'reb',
            'ast',
            'tov',
            'stl',
            'blk',
            'blka',
            'pf_team',
            'pfd',
            'plus_minus',
         ]);

            Team::updateOrCreate(
               ['name' => $team['name']],
               $team
            );
        }
    }
}